factset/AgDatabaseMove

- build/azure-pipelines.yml
It looks like you need to include tags explicitly: 
https://stackoverflow.com/questions/52615283/how-do-you-trigger-a-build-in-azure-pipelines-when-a-new-tag-is-pushed-to-github
The docs seem to indicate otherwise though:
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#tags
> include tags explicitly

- src/AgDatabaseMove.csproj
When referencing the package from a .NET Framework application run time errors occurred due assembly version conflicts in SMO. Multi targeting this library resolves those conflicts.
> chore(build): multi target net framework as well as net standard

- src/AgDatabaseMove.csproj
SqlManagementObjects publishes signed dll and the SMO package does not. This causes errors with shared references in down stream projects.
> chore(deps): switch to using SqlManagementObjects package

- src/Restore.cs
- tests/AgDatabaseMove.Integration/TestRestore.cs
- tests/AgDatabaseMove.Unit/RestoreTests.cs
* Default databases weren't set as expected in the integration environment. Ensure we set a default (master) for any logins we're moving.
* Our fillTable script wasn't generating enough load to put the secondaries in the initializing state.
> fix(tests): integration tests were broken

- src/Restore.cs
- src/SmoFacade/AvailabilityGroup.cs
- src/SmoFacade/Server.cs
- tests/AgDatabaseMove.Integration/Fixtures/TestLoginFixture.cs
- tests/AgDatabaseMove.Integration/TestLogin.cs
- tests/AgDatabaseMove.Unit/RestoreTests.cs
SQL Server treats several things as case insensitive, but we were using case sensitive comparisons for them within our application. The replica name in particular caused issues for me.
> fix(case): use case insensitive comparisons

- src/AgDatabase.cs
- src/AgDatabaseMove.cs
- src/SmoFacade/BackupFileTools.cs
- src/SmoFacade/Server.cs
- tests/AgDatabaseMove.Unit/FileToolsTest.cs
Fixed regex to allow underscores, basically by defining a directory path as anything non-whitespace
Two TODO questions:
1. Should we consider allowing a SQL query for _backupPathTemplate?  Angelo's backups deployement scripts don't update `SMO.Server.BackupDirectory`.  Options to fix would be (1) update that registry value in Angelo's scripts (2) allow CLI option to pass in query for value (3) don't worry about it because the backupPathTemplate should be used
2. Should the source DB be altered to single-user mode prior to the move?  Is that expected to be done by the consuming code?
> fix(regex): fix regex and cleanup after some testing

- src/AgDatabaseMove.cs
Setting this new option to `false` would allow a "copy/clone" instead of a "move"
> feat(options): delete source on move

- src/AgDatabase.cs
- src/DatabaseConfig.cs
- src/SmoFacade/Server.cs
Instead of passing in a string of the backup path template, pass in a string that is a SQL query to fetch the location.
If no text is present, then the fallback is `_server.BackupDirectory`
The query allows more flexibility on where consumers store their backup paths.
Note: the default value for `BackupPathSqlQuery` could probably be removed as that's more CRDS specific
> Feat(options): backup path sql query

- src/AgDatabase.cs
- src/DatabaseConfig.cs
- src/SmoFacade/Listener.cs
- src/SmoFacade/Server.cs
SqlServer <= 2012 doesn't support SAS tokens for backup/restore operations. 
Credential name is required in this case
https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url?view=sql-server-ver15#sqlserver
> feat(cred): explicit credential name

- src/SmoFacade/Listener.cs
- tests/AgDatabaseMove.Unit/SmoFacadeListenerTest.cs
`Dns.GetHostEntry(instance)` fails intermittently on linux platforms if `instance` doesn't have the full domain
> fix(linux_dns_issue): Re-trying DNS lookup of instance name after appending the domain from AG listener

- src/AgDatabaseMove.csproj
- src/SmoFacade/Listener.cs
ref: https://github.com/factset/AgDatabaseMove/pull/57#pullrequestreview-578899515
> refactor(listener): internalsVisibleTo moved to csproj and small changes in comments

- src/BackupChain.cs
- src/BackupMetadata.cs
- tests/AgDatabaseMove.Unit/BackupOrder.cs
Sometimes backups are split into multiple files (called `striped` backup), we need all of them for the restore process.
ref: https://www.sqlservercentral.com/articles/getting-a-list-of-the-striped-backup-files
> fix(striped_backups): changed logic to get all striped backups

- src/BackupChain.cs
- src/SmoFacade/BackupFileTools.cs
- src/SmoFacade/Server.cs
- tests/AgDatabaseMove.Unit/FileToolsTest.cs
Before, `Path.IsPathRooted(meta.PhysicalDeviceName);` would return false for Windows UNC paths on Unix runtime due to a difference in dotnet's implementation of the function for the diff runtimes:
Windows Runtime: https://github.com/dotnet/runtime/blob/44f8f0faee42367bdd39277d8295f6e914ad7f4a/src/libraries/System.Private.CoreLib/src/System/IO/Path.Windows.cs#L194 
vs.
Unix Runtime: https://github.com/dotnet/runtime/blob/44f8f0faee42367bdd39277d8295f6e914ad7f4a/src/libraries/System.Private.CoreLib/src/System/IO/Path.Unix.cs#L113
This would lead to backup files being filtered out and an exception being thrown during the creation of the backup chain.
Now we use the `IsUnc` property of the `Uri` class to detect UNC paths and since UNCs have to be fully-qualified by design, we can validate …
> fix(IsValidFilePath): Can now validate Windows UNC paths on Unix runtime

- src/SmoFacade/Database.cs
if you use `@@servername` in the filter, then the backupChain is not retrieved correctly for databases restored from another server
> fix(rollback): servername filter on query

- build/azure-pipelines.yml
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
##[warning]The windows-2016 environment is deprecated and will be removed on March 15, 2022. Migrate to windows-latest instead. For more details, see https://github.com/actions/virtual-environments/issues/4312
Closes #84
> fix(ci): azure pipeline vm image

- src/SmoFacade/Database.cs
4 retries starting at 10ms:
10ms, 100ms, 1000ms (1 second) 
6 retries starting at 5ms:
5ms, 25ms, 125ms, 625ms, 3125ms (3.1 seconds), 15625ms (15.625 seconds)
> feat(polly): retry db drop wait longer

- src/AgDatabase.cs
- src/SmoFacade/Login.cs
- src/SmoFacade/Server.cs
- tests/AgDatabaseMove.Integration/Config/TestAgDatabaseConfig.cs
- tests/AgDatabaseMove.Integration/Fixtures/TestAgDatabaseFixture.cs
- tests/AgDatabaseMove.Integration/TestAgDatabase.cs
Added functionality to create a new Sql login replicated on all replicas of an availability group. Requires creation of login on primary, saving SID, then using the saved SID to create the same login on secondary's.
Currently extends `AddLogin` to detect a case where caller may be trying to create a Sql login which does not yet exist. 
Added integration test for `AgDatabase` to test functionality described above. Tests for existence of logins, logins are created on more than just the primary, and verifies Sid of logins match.
These changes pass the tests included. I also manually verified creation of logins with matching Sid on each replica of availability group.
> feat(login): create new sql login

- src/AgDatabase.cs
- src/AgDatabaseMove.cs
- src/SmoFacade/Database.cs
- src/SmoFacade/Listener.cs
- src/SmoFacade/Server.cs
Made changes to `Restore` to rename logical files using `fileRelocator` when passed in.
Tested in separate console application, verified logical names had changed in SSMS
> feat(restore): logical file rename

- src/AgDatabase.cs
- src/SmoFacade/Database.cs
> fix(backups): no full backup

- src/BackupChain.cs
- src/BackupMetadata.cs
(It looks like it made loads of white space changes automatically - pls ignore this while reviewing.)
I came across an instance where the `LastLsn` was the same for 2 backups. Hence, this check was filtering the log backup out.
> fix(backup-chain): next log backup can have the same `LastLsn`

- src/AgDatabaseMove.cs
Need to remove this line.
We have some cases where we are trying to rename a file to itself, causing exceptions
> fix(move): rename logical file name

- src/SmoFacade/BackupFileTools.cs
- src/SmoFacade/Server.cs
- tests/AgDatabaseMove.Unit/FileToolsTest.cs
Quick and easy alternative to relying on `System.IO.Path` file separators.
> fix(path): separators

- src/AgDatabase.cs
- src/AgDatabaseMove.cs
- src/BackupChain.cs
- src/BackupMetadata.cs
- src/SmoFacade/Database.cs
- src/SmoFacade/Server.cs
- tests/AgDatabaseMove.Integration/TestRestore.cs
- tests/AgDatabaseMove.Unit/BackupOrder.cs
- tests/AgDatabaseMove.Unit/StripedBackupSetTests.cs
I was running into an error with the backup chain construction on a sample of backups identical (in their order) to the example I've provided below as a unit test. I've included a fix in here that passes the provided unit test, but wanted to get additional eyes on this to verify the change shouldn't effect how backups are being ordered in other use cases.
Specifically, the variables used within the `while` loop would change as follows:
First Iteration
----
`orderedBackups `= [full, diff]
`prevBackup `= diff
`nextLog `= [log2, log1]
Second Iteration
----
`orderedBackups `= [full, diff, log2, log1]
`prevBackup `= log1
`nextLog `= [log2]
....
Such that the resulting `orderedBackups` = [full, diff, log2, log1, log2, ...]. This would result in a bug in which a striped backup chain built from …
> fix(backupchain): diff and log share last lsn

- src/AgDatabase.cs
- src/SmoFacade/Server.cs
- tests/AgDatabaseMove.Integration/TestRestore.cs
Created an overload for `Restore` that takes in a full `SingleBackup`. This can be used to restore databases that can be effectively recovered under the simple recovery model. Added a couple integration tests and verified they passed.
> feat(Restore): single backup

- build/azure-pipelines.yml
Build had been failing with the message:
```
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
...
Test Run Aborted.
##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1
Result Attachments will be stored in LogStore
Run Attachments will be stored in LogStore
No Result Found to Publish 'D:\a\_temp\VssAdministrator_fv-az2425-926_2023-09-13_19_00_57.trx'.
##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli …
```
> fix(build): UseDotNet

- src/AgDatabase.cs
- src/SmoFacade/Listener.cs
- tests/AgDatabaseMove.Integration/Fixtures/TestAgDatabaseFixture.cs
- tests/AgDatabaseMove.Integration/TestAgDatabase.cs
- tests/AgDatabaseMove.Integration/TestRestore.cs
I have a need for the internals of `IListener` to be made public. Specifically, I'm trying to avoid having to re-write code to get the names of/connections to replicas in an availability group.
The concrete implementation `Listener` is still internal and therefore can't be directly instantiated... I believe that should be sufficient protection.
> feat(IListener): visibility

- src/SmoFacade/Login.cs
Fixes the issue described in https://www.tarynpivots.com/post/system-view-gotcha-with-sql-server-2019/.
In SqlServer 2019, the _sys.syslogins_ view returns `NULL` for the `password` field. _sys.sql_logins_ should be used instead.
Should continue to work for older version of SqlServer as well.
> fix(syslogins): password NULL
